name: Daily BTC Fetch

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:      # Allows manual trigger from GitHub

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make script executable and run it
        run: |
          chmod +x ./fetch_and_commit.sh
          ./fetch_and_commit.sh

      - name: Commit and push data changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*
          git commit -m "Daily BTC price commit on $(date)" || echo "No changes to commit"
          git push https://github.com/piyush60629/btc-fetcher.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
